"""Generate docs/eda/DATASETS.md summarizing every file in data/processed/."""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ai_agents"))
from scripts_lib.eda import summarize_df  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
rows = []
files = sorted((ROOT / "data" / "processed").glob("*")) + sorted(
    (ROOT / "data" / "raw").glob("*.csv")  # kaggle CSVs land in raw/
)
for p in files:
    if p.suffix == ".parquet":
        rows.append(summarize_df(p.name, pd.read_parquet(p)))
    elif p.suffix == ".csv":
        rows.append(summarize_df(p.name, pd.read_csv(p, encoding_errors="replace")))

lines = [
    "# Dataset Inventory (auto-generated by scripts/eda_report.py)",
    "",
    "| File | Rows | Cols | Null % |",
    "| --- | --- | --- | --- |",
]
lines += [f"| {r['name']} | {r['rows']:,} | {r['cols']} | {r['null_pct']} |" for r in rows]
(ROOT / "docs" / "eda" / "DATASETS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("\n".join(lines))
